Repository Pick-px/frontend, pull requests merged in 2025-07, with the labels that each got.

#60 [SCRUM-104] login-chatopen
  src/components/chat/Chat.tsx
Labels: feat

#63 [SCRUM-107]: 로그인시 Navigate 에 canvas_id 반영
  src/auth/AuthCallbackPage.tsx
  src/components/modal/LoginModalContent.tsx
Labels: fix

#64 [SCRUM-96] 그룹 모달 검증 및 오류 수정
  src/api/GroupAPI.tsx
  src/components/group/GroupCreateTab.tsx
  src/components/group/GroupJoinTab.tsx
  src/components/group/GroupListTab.tsx
  src/components/modal/GroupModalContent.tsx
  src/components/modal/Modal.tsx
Labels: feat

#71 [SCRUM-117]: 게임 방법 설명 toast Msg 추가
  public/bg_thumbnail.png
  public/bl_thumbnail.png
  src/App.tsx
  src/components/CanvasUI.tsx
  src/components/PixelCanvas.tsx
  src/components/toast/InstructionsToast.tsx
Labels: feat

#72 [SCRUM-113] 캔버스 모달 ui 및 기능 구현
  src/App.tsx
  src/api/CanvasAPI.ts
  src/api/CanvasAPI.tsx
  src/api/GroupAPI.ts
  src/components/CanvasUI.tsx
  src/components/modal/CanvasModalContent.tsx
Labels: feat

#113 [SCRUM-163] Album 모달 기능 구현, 도움말 모달 추가 및 소켓 쿠키 저장 설정 추가
  src/App.tsx
  src/components/album/AlbumDetailModal.tsx
  src/components/album/AlbumItem.tsx
  src/components/album/AlbumList.tsx
  src/components/album/albumAPI.ts
  src/components/album/albumTypes.ts
  src/components/canvas/CanvasUIMobile.tsx
  src/components/canvas/CanvasUIPC.tsx
  src/components/chat/ChatAPI.tsx
  src/components/modal/AlbumModalContent.tsx
  src/components/modal/HelpModalContent.tsx
  src/services/socketService.ts
  src/store/modalStore.ts
Labels: feat

#119 [SCRUM-180] 접속자수 표시 기능 구현
  src/components/canvas/CanvasUIPC.tsx
  src/components/canvas/UserCount.tsx
  src/services/socketService.ts
Labels: feat

#142 [SRCUM-228]]PixelCanvas.tsx 렌더링 로직 분리
  index.html
  src/components/canvas/PixelCanvas.tsx
  src/components/canvas/StarfieldCanvas.tsx
  src/setupTests.ts
  src/utils/ImageEditorUI.tsx
  src/utils/canvasDrawing.ts
  src/utils/starfieldUtils.ts
Labels: refactor

#146 [SCRUM-230] gamemode 404 error
  src/components/game/GameCanvas.tsx
Labels: fix

#157 [Fix] 접속자수 툴팁 추가 및 도움말 버튼 위치 수정
  src/components/canvas/CanvasUIPC.tsx
  src/components/canvas/UserCount.tsx
  src/components/modal/MyPageModalContent.tsx
Labels: fix

#159 [SCRUM-248] 문제 모달 엔터키 버그 수정
  src/components/game/GameCanvas.tsx
  src/hooks/useCanvasInteraction.ts
Labels: fix

#161 [SCRUM-250] 모바일 환경 채팅창 스크롤 기능 추가
  src/components/chat/Chat.tsx
  src/components/chat/MessageList.tsx
Labels: fix
